import {
  LayoutDashboard,
  Sparkles,
  NotebookPen,
  ListChecks,
  BarChart3,
  Calculator,
  Globe2,
  Bell,
  Settings,
  Users,
  CreditCard,
  Cpu,
  LineChart,
  Megaphone,
  ShieldCheck,
  Activity,
  SlidersHorizontal,
  Plug,
  Landmark,
  BadgeCheck,
  MessagesSquare,
  UsersRound,
  Target,
  Gauge,
  Swords,
} from 'lucide-react';

export const traderNav = [
  { to: '/app/dashboard', label: 'Dashboard', icon: LayoutDashboard },
  { to: '/app/ai', label: 'Kotka AI', icon: Sparkles },
  { to: '/app/journal', label: 'Journal', icon: NotebookPen },
  { to: '/app/checklist', label: 'Checklist', icon: ListChecks },
  { to: '/app/goals', label: 'Goal Room', icon: Target },
  { to: '/app/analytics', label: 'Analytics', icon: BarChart3 },
  { to: '/app/calculators', label: 'Calculators', icon: Calculator },
  { to: '/app/market', label: 'Market Intelligence', icon: Globe2 },
  { to: '/app/game', label: 'Trading Game', icon: Swords },
  { to: '/app/community', label: 'Community', icon: MessagesSquare },
];

export const traderNavSecondary = [
  { to: '/app/notifications', label: 'Notifications', icon: Bell },
  { to: '/app/settings', label: 'Settings', icon: Settings },
];

export const adminNav = [
  { to: '/admin/overview', label: 'Overview', icon: LayoutDashboard },
  { to: '/admin/users', label: 'Users', icon: Users },
  { to: '/admin/verifications', label: 'Verifications', icon: BadgeCheck },
  { to: '/admin/community', label: 'Community', icon: UsersRound, moderator: true },
  { to: '/admin/announcements', label: 'Announcements', icon: Megaphone },
  { to: '/admin/research', label: 'Fundamental Research', icon: Landmark },
  { to: '/admin/usage', label: 'Usage Control', icon: Gauge },
  { to: '/admin/game', label: 'Trading Game', icon: Swords },
  { to: '/admin/ai-usage', label: 'AI Usage', icon: Cpu },
  { to: '/admin/trading-stats', label: 'Trading Statistics', icon: LineChart },
  { to: '/admin/journal-stats', label: 'Journal Statistics', icon: NotebookPen },
  { to: '/admin/billing', label: 'Plans & Billing', icon: CreditCard },
  { to: '/admin/system-health', label: 'System Status', icon: Activity },
  { to: '/admin/audit-logs', label: 'Audit Log', icon: ShieldCheck },
  { to: '/admin/integrations', label: 'Connected services', icon: Plug, superAdminOnly: true },
  { to: '/admin/settings', label: 'Platform Settings', icon: SlidersHorizontal, superAdminOnly: true },
];
