import {
  LayoutDashboard,
  Sparkles,
  NotebookPen,
  ListChecks,
  BarChart3,
  Calculator,
  Globe2,
  Dna,
  Gamepad2,
  History,
  Bell,
  Settings,
  Users,
  CreditCard,
  Cpu,
  LineChart,
  DollarSign,
  FileBarChart,
  Megaphone,
  BookOpen,
  Newspaper,
  Flag,
  LifeBuoy,
  ShieldCheck,
  Activity,
  Server,
  SlidersHorizontal,
} from 'lucide-react';

export const traderNav = [
  { to: '/app/dashboard', label: 'Dashboard', icon: LayoutDashboard },
  { to: '/app/ai', label: 'Kotka AI', icon: Sparkles },
  { to: '/app/journal', label: 'Journal', icon: NotebookPen },
  { to: '/app/checklist', label: 'Checklist', icon: ListChecks },
  { to: '/app/analytics', label: 'Analytics', icon: BarChart3 },
  { to: '/app/calculators', label: 'Calculators', icon: Calculator },
  { to: '/app/market', label: 'Market Intelligence', icon: Globe2 },
  { to: '/app/trader-dna', label: 'Trader DNA', icon: Dna, premium: true },
  { to: '/app/simulator', label: 'Simulator', icon: Gamepad2 },
  { to: '/app/replay', label: 'Replay Engine', icon: History, premium: true },
];

export const traderNavSecondary = [
  { to: '/app/notifications', label: 'Notifications', icon: Bell },
  { to: '/app/settings', label: 'Settings', icon: Settings },
];

export const adminNav = [
  { to: '/admin/overview', label: 'Overview', icon: LayoutDashboard },
  { to: '/admin/users', label: 'Users', icon: Users },
  { to: '/admin/subscriptions', label: 'Subscriptions', icon: CreditCard },
  { to: '/admin/ai-usage', label: 'AI Usage', icon: Cpu },
  { to: '/admin/trading-stats', label: 'Trading Statistics', icon: LineChart },
  { to: '/admin/journal-stats', label: 'Journal Statistics', icon: NotebookPen },
  { to: '/admin/simulator-stats', label: 'Simulator Statistics', icon: Gamepad2 },
  { to: '/admin/revenue', label: 'Revenue', icon: DollarSign },
  { to: '/admin/reports', label: 'Reports', icon: FileBarChart },
  { to: '/admin/announcements', label: 'Announcements', icon: Megaphone },
  { to: '/admin/content', label: 'Content', icon: BookOpen },
  { to: '/admin/courses', label: 'Courses', icon: BookOpen },
  { to: '/admin/market-news', label: 'Market News', icon: Newspaper },
  { to: '/admin/feature-flags', label: 'Feature Flags', icon: Flag },
  { to: '/admin/support', label: 'Support Tickets', icon: LifeBuoy },
  { to: '/admin/audit-logs', label: 'Audit Logs', icon: ShieldCheck },
  { to: '/admin/system-health', label: 'System Health', icon: Activity },
  { to: '/admin/api-usage', label: 'API Usage', icon: Server },
  { to: '/admin/settings', label: 'Settings', icon: SlidersHorizontal },
];
