import { Sparkles, CreditCard, Globe2, Landmark, CalendarClock, Mail, Wallet, HardDrive } from 'lucide-react';

export const INTEGRATION_PROVIDERS = [
  {
    id: 'nvidia',
    name: 'NVIDIA',
    category: 'Artificial Intelligence',
    icon: Sparkles,
    description: 'Powers Kotka AI: chat, reading chart screenshots, journal reviews and the written summaries in Fundamental Research.',
    fallbackNote:
      'If NVIDIA retires or pauses a model, Kotka switches to a working one by itself and notes it below. It re-checks every model every 6 hours, so you rarely need to change anything here.',
    fields: [
      { key: 'secret', label: 'Access key', type: 'password', placeholder: 'Starts with nvapi-', hint: 'From your NVIDIA account at build.nvidia.com.' },
      {
        key: 'config.model',
        label: 'Chat model (advanced)',
        type: 'text',
        placeholder: 'nvidia/nemotron-3-super-120b-a12b',
        hint: 'Leave as is unless you want a different model. Tested and working: nvidia/nemotron-3-super-120b-a12b, nvidia/nemotron-3-ultra-550b-a55b, moonshotai/kimi-k3.',
        default: 'nvidia/nemotron-3-super-120b-a12b',
      },
      {
        key: 'config.chatFallbacks',
        label: 'Backup chat models (optional)',
        type: 'text',
        placeholder: 'Separate with commas, tried in order',
        hint: 'Used if the chat model stops working, before Kotka’s own tested list.',
      },
      {
        key: 'config.visionModel',
        label: 'Chart-reading model (advanced)',
        type: 'text',
        placeholder: 'meta/llama-3.2-11b-vision-instruct',
        hint: 'Reads chart screenshots traders upload. Tested and working: meta/llama-3.2-11b-vision-instruct, nvidia/nemotron-3-nano-omni-30b-a3b-reasoning.',
        default: 'meta/llama-3.2-11b-vision-instruct',
      },
      {
        key: 'config.visionFallbacks',
        label: 'Backup chart-reading models (optional)',
        type: 'text',
        placeholder: 'Separate with commas, tried in order',
      },
      {
        key: 'config.baseUrl',
        label: 'Service address (advanced)',
        hint: 'Only change this if NVIDIA tells you to.',
        type: 'text',
        default: 'https://integrate.api.nvidia.com/v1',
      },
    ],
  },
  {
    id: 'whop',
    name: 'Whop',
    category: 'Payments',
    icon: Wallet,
    description: 'The main way money goes in and out of Trading Game wallets: deposits by checkout, withdrawals to each trader’s Whop payout account.',
    fallbackNote: 'Without it (and without Paystack switched on in Admin → Trading Game), deposits and withdrawals say they aren’t set up yet. Practice matches still work.',
    fields: [
      { key: 'secret', label: 'API key', type: 'password', placeholder: 'Your Whop company API key', hint: 'Whop dashboard → Developer → API keys. It needs checkout, payments, companies, account links and transfers permissions.' },
      { key: 'config.companyId', label: 'Company id', type: 'text', placeholder: 'Starts with biz_', hint: 'Whop dashboard → Settings. Payouts come from this company’s balance.' },
      { key: 'config.webhookSecret', label: 'Webhook secret', type: 'password', placeholder: 'Starts with ws_', hint: 'From the webhook you create in Whop pointing at https://www.kotkafinance.online/api/game/webhooks/whop (events payment.succeeded and payment.failed). Stored encrypted.' },
    ],
  },
  {
    id: 'paystack',
    name: 'Paystack',
    category: 'Payments',
    icon: CreditCard,
    description: 'An optional second way to pay into and out of Trading Game wallets (switch it on in Admin → Trading Game).',
    fallbackNote: 'Without it, Whop is the only payment option.',
    fields: [
      { key: 'secret', label: 'Secret key', type: 'password', placeholder: 'Starts with sk_live_ (or sk_test_ for testing)', hint: 'Paystack dashboard → Settings → API keys.' },
      { key: 'publicKey', label: 'Public key', type: 'text', placeholder: 'Starts with pk_live_ (or pk_test_)' },
    ],
  },
  {
    id: 'finnhub',
    name: 'Finnhub',
    category: 'Market Data',
    icon: Globe2,
    description: 'Supplies the market news headlines in Community.',
    fallbackNote: 'Without it, Community still shows official central-bank news, but no wire headlines.',
    fields: [{ key: 'secret', label: 'Access key', type: 'password', placeholder: 'Your Finnhub key', hint: 'From your Finnhub dashboard.' }],
  },
  {
    id: 'massive',
    name: 'Massive',
    category: 'Market Data',
    icon: Globe2,
    description: 'Daily closing prices for forex, gold, silver, indices and crypto: the market pulse, market rooms and price moves in research.',
    fallbackNote: 'Without it, prices show as unavailable. Kotka never fills in made-up prices.',
    fields: [{ key: 'secret', label: 'Access key', type: 'password', placeholder: 'Your Massive key', hint: 'Massive was previously called Polygon.io.' }],
  },
  {
    id: 'fred',
    name: 'FRED',
    category: 'Economic Data',
    icon: Landmark,
    description: 'US economic data from the Federal Reserve Bank of St. Louis: interest rates, inflation, growth, jobs and bond yields for Fundamental Research.',
    fallbackNote: 'Optional. Research works without it; a key just makes loading the US data more reliable.',
    fields: [{ key: 'secret', label: 'Access key', type: 'password', placeholder: 'Free at fred.stlouisfed.org' }],
  },
  {
    id: 'cronjob',
    name: 'cron-job.org',
    category: 'Scheduling',
    icon: CalendarClock,
    description: 'Runs Kotka’s hourly update: refreshing research, news, events and reminders, and checking the AI models still work.',
    fallbackNote: 'With a key here, Kotka keeps the schedule set up for you. Without one, you paste the update link into cron-job.org yourself (Admin → Fundamental Research).',
    fields: [{ key: 'secret', label: 'Access key', type: 'password', placeholder: 'From cron-job.org → Console → Settings' }],
  },
  {
    id: 'resend',
    name: 'Resend',
    category: 'Email',
    icon: Mail,
    description: 'Sends Kotka’s account emails from no-reply@kotkafinance.online: welcome and email confirmation, password resets, and security alerts.',
    fallbackNote: 'Without it (or INBOX as a backup), people can’t reset a forgotten password by email and get no security alerts.',
    fields: [{ key: 'secret', label: 'API key', type: 'password', placeholder: 'Starts with re_', hint: 'Resend → API Keys. The kotkafinance.online domain must be verified in Resend.' }],
  },
  {
    id: 'inbox',
    name: 'INBOX',
    category: 'Email',
    icon: Mail,
    description: 'Keeps the Kotka newsletter list in INBOX up to date (only traders who opt in), and sends account emails through INBOX Notify if Resend is down.',
    fallbackNote: 'INBOX’s API signs in with your INBOX account email and password; there’s no separate API key. They are stored encrypted like every other key.',
    fields: [
      { key: 'publicKey', label: 'INBOX account email', type: 'email', placeholder: 'The email you sign in to INBOX with' },
      { key: 'secret', label: 'INBOX account password', type: 'password', placeholder: 'Your INBOX password' },
      { key: 'config.listId', label: 'Newsletter list id', type: 'text', placeholder: 'Shown by Test connection once signed in', hint: 'The INBOX contact list opted-in traders are added to.' },
      { key: 'config.senderEmail', label: 'Backup sender address (optional)', type: 'email', placeholder: 'e.g. no-reply@kotkafinance.online', hint: 'Must be a sender you’ve added and activated in INBOX Notify.' },
    ],
  },
  {
    id: 'r2',
    name: 'Cloudflare R2',
    category: 'File storage',
    icon: HardDrive,
    description: 'Stores photos, voice notes and achievement share cards. Files stay private: Kotka serves each one only to people allowed to see it.',
    fallbackNote: 'Without it, uploads are kept in the database, which fills up quickly. Don’t connect this bucket to www.kotkafinance.online as a custom domain: that takes the app offline.',
    fields: [
      { key: 'config.accountId', label: 'Cloudflare account ID', type: 'text', placeholder: '32 characters', hint: 'Cloudflare dashboard → R2 → the account ID on the right.' },
      { key: 'config.accessKeyId', label: 'Access key ID', type: 'text', placeholder: 'From R2 → Manage API tokens' },
      { key: 'secret', label: 'Secret access key', type: 'password', placeholder: 'Shown once when the R2 token is created' },
      { key: 'config.bucket', label: 'Bucket name', type: 'text', placeholder: 'kotka', default: 'kotka' },
      { key: 'config.prefix', label: 'Folder in the bucket', type: 'text', placeholder: 'media', default: 'media', hint: 'Keep production and test copies in different folders.' },
    ],
  },
];
