import { Sparkles, CreditCard, Globe2, Landmark, CalendarClock } from 'lucide-react';

export const INTEGRATION_PROVIDERS = [
  {
    id: 'nvidia',
    name: 'NVIDIA',
    category: 'Artificial Intelligence',
    icon: Sparkles,
    description: 'Powers Kotka AI: chat, reading chart screenshots, journal reviews and the written summaries in Fundamental Research.',
    fallbackNote:
      'If NVIDIA retires or pauses a model, Kotka switches to a working one by itself and notes it below. It re-checks every model every 6 hours, so you rarely need to change anything here.',
    fields: [
      { key: 'secret', label: 'Access key', type: 'password', placeholder: 'Starts with nvapi-', hint: 'From your NVIDIA account at build.nvidia.com.' },
      {
        key: 'config.model',
        label: 'Chat model (advanced)',
        type: 'text',
        placeholder: 'nvidia/nemotron-3-super-120b-a12b',
        hint: 'Leave as is unless you want a different model. Tested and working: nvidia/nemotron-3-super-120b-a12b, nvidia/nemotron-3-ultra-550b-a55b, moonshotai/kimi-k3.',
        default: 'nvidia/nemotron-3-super-120b-a12b',
      },
      {
        key: 'config.chatFallbacks',
        label: 'Backup chat models (optional)',
        type: 'text',
        placeholder: 'Separate with commas, tried in order',
        hint: 'Used if the chat model stops working, before Kotka’s own tested list.',
      },
      {
        key: 'config.visionModel',
        label: 'Chart-reading model (advanced)',
        type: 'text',
        placeholder: 'meta/llama-3.2-11b-vision-instruct',
        hint: 'Reads chart screenshots traders upload. Tested and working: meta/llama-3.2-11b-vision-instruct, nvidia/nemotron-3-nano-omni-30b-a3b-reasoning.',
        default: 'meta/llama-3.2-11b-vision-instruct',
      },
      {
        key: 'config.visionFallbacks',
        label: 'Backup chart-reading models (optional)',
        type: 'text',
        placeholder: 'Separate with commas, tried in order',
      },
      {
        key: 'config.baseUrl',
        label: 'Service address (advanced)',
        hint: 'Only change this if NVIDIA tells you to.',
        type: 'text',
        default: 'https://integrate.api.nvidia.com/v1',
      },
    ],
  },
  {
    id: 'paystack',
    name: 'Paystack',
    category: 'Payments',
    icon: CreditCard,
    description: 'Takes payments for Pro and Institutional plans.',
    fallbackNote: 'Without it, traders can’t upgrade or pay, and billing options stay hidden.',
    fields: [
      { key: 'secret', label: 'Secret key', type: 'password', placeholder: 'Starts with sk_live_ (or sk_test_ for testing)', hint: 'Paystack dashboard → Settings → API keys.' },
      { key: 'publicKey', label: 'Public key', type: 'text', placeholder: 'Starts with pk_live_ (or pk_test_)' },
    ],
  },
  {
    id: 'finnhub',
    name: 'Finnhub',
    category: 'Market Data',
    icon: Globe2,
    description: 'Supplies the market news headlines in Community.',
    fallbackNote: 'Without it, Community still shows official central-bank news, but no wire headlines.',
    fields: [{ key: 'secret', label: 'Access key', type: 'password', placeholder: 'Your Finnhub key', hint: 'From your Finnhub dashboard.' }],
  },
  {
    id: 'massive',
    name: 'Massive',
    category: 'Market Data',
    icon: Globe2,
    description: 'Daily closing prices for forex, gold, silver, indices and crypto: the market pulse, market rooms and price moves in research.',
    fallbackNote: 'Without it, prices show as unavailable. Kotka never fills in made-up prices.',
    fields: [{ key: 'secret', label: 'Access key', type: 'password', placeholder: 'Your Massive key', hint: 'Massive was previously called Polygon.io.' }],
  },
  {
    id: 'fred',
    name: 'FRED',
    category: 'Economic Data',
    icon: Landmark,
    description: 'US economic data from the Federal Reserve Bank of St. Louis: interest rates, inflation, growth, jobs and bond yields for Fundamental Research.',
    fallbackNote: 'Optional. Research works without it; a key just makes loading the US data more reliable.',
    fields: [{ key: 'secret', label: 'Access key', type: 'password', placeholder: 'Free at fred.stlouisfed.org' }],
  },
  {
    id: 'cronjob',
    name: 'cron-job.org',
    category: 'Scheduling',
    icon: CalendarClock,
    description: 'Runs Kotka’s hourly update: refreshing research, news, events and reminders, and checking the AI models still work.',
    fallbackNote: 'With a key here, Kotka keeps the schedule set up for you. Without one, you paste the update link into cron-job.org yourself (Admin → Fundamental Research).',
    fields: [{ key: 'secret', label: 'Access key', type: 'password', placeholder: 'From cron-job.org → Console → Settings' }],
  },
];
