import { Sparkles, CreditCard, Globe2, Landmark, CalendarClock } from 'lucide-react';

export const INTEGRATION_PROVIDERS = [
  {
    id: 'nvidia',
    name: 'NVIDIA',
    category: 'Artificial Intelligence',
    icon: Sparkles,
    description: 'NVIDIA NIM / build.nvidia.com. Powers Kotka AI chat, chart image analysis, journal critiques and Fundamental Research narratives.',
    fallbackNote:
      'If a configured model is retired or unavailable, Kotka automatically switches to the next model in the fallback list, then to its vetted defaults, and records the switch below. A scheduled health check re-tests every model every 6 hours.',
    fields: [
      { key: 'secret', label: 'API Key', type: 'password', placeholder: 'nvapi-…' },
      {
        key: 'config.model',
        label: 'Chat Model',
        type: 'text',
        placeholder: 'nvidia/nemotron-3-super-120b-a12b',
        hint: 'Must support streaming and tool calling. Verified: nvidia/nemotron-3-super-120b-a12b, nvidia/nemotron-3-ultra-550b-a55b, moonshotai/kimi-k3.',
        default: 'nvidia/nemotron-3-super-120b-a12b',
      },
      {
        key: 'config.chatFallbacks',
        label: 'Chat fallback models (optional)',
        type: 'text',
        placeholder: 'comma separated, tried in order',
        hint: 'Tried before the vetted defaults if the chat model fails.',
      },
      {
        key: 'config.visionModel',
        label: 'Vision Model',
        type: 'text',
        placeholder: 'meta/llama-3.2-11b-vision-instruct',
        hint: 'Used when a trader uploads a chart image. Verified: meta/llama-3.2-11b-vision-instruct, nvidia/nemotron-3-nano-omni-30b-a3b-reasoning.',
        default: 'meta/llama-3.2-11b-vision-instruct',
      },
      {
        key: 'config.visionFallbacks',
        label: 'Vision fallback models (optional)',
        type: 'text',
        placeholder: 'comma separated, tried in order',
      },
      {
        key: 'config.baseUrl',
        label: 'Base URL',
        type: 'text',
        default: 'https://integrate.api.nvidia.com/v1',
      },
    ],
  },
  {
    id: 'paystack',
    name: 'Paystack',
    category: 'Payments',
    icon: CreditCard,
    description: 'Processes Pro and Institutional subscription billing.',
    fallbackNote: 'Without an active Paystack connection, upgrade and billing actions are disabled platform-wide.',
    fields: [
      { key: 'secret', label: 'Secret Key', type: 'password', placeholder: 'sk_test_… or sk_live_…' },
      { key: 'publicKey', label: 'Public Key', type: 'text', placeholder: 'pk_test_… or pk_live_…' },
    ],
  },
  {
    id: 'finnhub',
    name: 'Finnhub',
    category: 'Market Data',
    icon: Globe2,
    description: 'Not used at the moment. Its free plan does not include forex quotes or the economic calendar; Kotka now uses Massive for prices and official central-bank and statistics calendars for events.',
    fallbackNote: 'Nothing depends on this connection. You can leave it disabled.',
    fields: [{ key: 'secret', label: 'API Key', type: 'password', placeholder: 'Finnhub API key' }],
  },
  {
    id: 'massive',
    name: 'Massive',
    category: 'Market Data',
    icon: Globe2,
    description: 'Formerly Polygon.io. End-of-day forex, metals, index and crypto bars for the market pulse (last close, daily change, 14-day ATR) and pair price performance in Fundamental Research.',
    fallbackNote: 'Without an active Massive connection, prices and volatility are shown as unavailable. Nothing is substituted.',
    fields: [{ key: 'secret', label: 'API Key', type: 'password', placeholder: 'Massive API key' }],
  },
  {
    id: 'fred',
    name: 'FRED',
    category: 'Economic Data',
    icon: Landmark,
    description: 'Federal Reserve Bank of St. Louis API: US policy rates, inflation, GDP, labour and yield series for Fundamental Research.',
    fallbackNote: 'Optional. Without a key, Fundamental Research reads the same official series from FRED’s public CSV endpoint; a key gives the documented JSON API and higher reliability.',
    fields: [{ key: 'secret', label: 'API Key', type: 'password', placeholder: 'FRED API key (free at fred.stlouisfed.org)' }],
  },
  {
    id: 'cronjob',
    name: 'cron-job.org',
    category: 'Scheduling',
    icon: CalendarClock,
    description: 'Runs the hourly job that refreshes Fundamental Research and re-tests the AI models. With a key here, rotating the cron token updates the job automatically.',
    fallbackNote: 'Without a key, the cron token must be copied into cron-job.org by hand after every rotation (Admin → Fundamental Research).',
    fields: [{ key: 'secret', label: 'API Key', type: 'password', placeholder: 'cron-job.org API key (Console → Settings)' }],
  },
];
