// Kotka's synthetic pairs. Each is made from Kotka's own synthetic assets
// (a token, a coin, metals, crude, an index, currency proxies), priced
// against a quote. They are not real markets and never follow real prices:
// every price is generated by market.js.
//
// level     typical price, around which a match's market starts
// decimals  price precision (what the chart and fills round to)
// vol       volatility relative to Kotka's base market (1 = normal)
// volume    typical volume per second, for the volume bars

export const ASSETS = {
  KTK: 'Kotka Token',
  KBC: 'Kotka Coin',
  KGD: 'Kotka Gold',
  KSV: 'Kotka Silver',
  KOL: 'Kotka Crude',
  K30: 'Kotka 30 Index',
  KEU: 'Kotka Euro',
  KGB: 'Kotka Pound',
  KUS: 'Kotka Dollar',
  NGN: 'Naira',
  USD: 'Dollar',
};

export const PAIRS = [
  { symbol: 'KTK/NGN', category: 'Tokens', level: 2150, decimals: 2, vol: 1.5, volume: 900 },
  { symbol: 'KTK/USD', category: 'Tokens', level: 1.3875, decimals: 4, vol: 1.5, volume: 1200 },
  { symbol: 'KBC/USD', category: 'Tokens', level: 64250, decimals: 1, vol: 1.8, volume: 80 },
  { symbol: 'KBC/NGN', category: 'Tokens', level: 99_500_000, decimals: 0, vol: 1.8, volume: 60 },
  { symbol: 'KBC/KTK', category: 'Crosses', level: 46300, decimals: 1, vol: 1.2, volume: 50 },
  { symbol: 'KGD/USD', category: 'Metals', level: 2365.4, decimals: 2, vol: 0.7, volume: 400 },
  { symbol: 'KGD/NGN', category: 'Metals', level: 3_666_000, decimals: 0, vol: 0.8, volume: 300 },
  { symbol: 'KSV/USD', category: 'Metals', level: 29.482, decimals: 3, vol: 1.1, volume: 700 },
  { symbol: 'KGD/KSV', category: 'Crosses', level: 80.24, decimals: 2, vol: 0.6, volume: 150 },
  { symbol: 'KOL/USD', category: 'Energy', level: 78.36, decimals: 2, vol: 1.2, volume: 1100 },
  { symbol: 'KOL/NGN', category: 'Energy', level: 121_450, decimals: 0, vol: 1.3, volume: 800 },
  { symbol: 'K30/NGN', category: 'Indices', level: 96_540, decimals: 1, vol: 0.9, volume: 500 },
  { symbol: 'KEU/USD', category: 'Currencies', level: 1.08745, decimals: 5, vol: 0.45, volume: 2500 },
  { symbol: 'KGB/USD', category: 'Currencies', level: 1.26980, decimals: 5, vol: 0.5, volume: 2000 },
  { symbol: 'KEU/KGB', category: 'Currencies', level: 0.85640, decimals: 5, vol: 0.35, volume: 1500 },
  { symbol: 'KUS/NGN', category: 'Currencies', level: 1549.5, decimals: 2, vol: 0.4, volume: 3000 },
].map((p) => {
  const [base, quote] = p.symbol.split('/');
  return { ...p, base, quote, name: `${ASSETS[base]} / ${ASSETS[quote]}` };
});

export const PAIR_SYMBOLS = PAIRS.map((p) => p.symbol);
export const pairOf = (symbol) => PAIRS.find((p) => p.symbol === symbol) ?? null;
export const publicPair = (p) => (p ? { symbol: p.symbol, name: p.name, category: p.category, decimals: p.decimals, base: p.base, quote: p.quote } : null);
